### ISSUE TITLE
Hola, ¿Es este repositorio de Jose Ignacio, García Troncoso?

### ISSUE THREAD

**Issue by VAMarques** [josegdotcom/imt2200-actividad-2024#1]
Tengo la sospecha de que el repositorio te pertenece, despues de todo eres el unico Jose en el curso, aun asi me gustaria una confirmacion. Seria buena idea que pongas tu nombre real en el Readme, y no solo un Shrek Musculoso (No digo que elimines el shrek musculoso, pero es mejor que tenga tu nombre)

**Comment by josegdotcom** [comment]
Pues si me pertenece, José García Troncoso y ok, es que estaba experimentando perdón.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: VAMarques ***@***.***>
Sent: Friday, August 9, 2024 10:52:58 PM
To: josegdotcom/imt2200---actividad-01 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [josegdotcom/imt2200---actividad-01] Hola, ¿Es este repositorio de Jose Ignacio, García Troncoso? (Issue #1)

No suele recibir correos electrónicos de ***@***.*** Por qué esto es importante<https://aka.ms/LearnAboutSenderIdentification>

Tengo la sospecha de que el repositorio te pertenece, despues de todo eres el unico Jose en el curso, aun asi me gustaria una confirmacion. Seria buena idea que pongas tu nombre real en el Readme, y no solo un Shrek Musculoso (No digo que elimines el shrek musculoso, pero es mejor que tenga tu nombre)
